routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/',[EmployeeController::class, 'index']);

Route::resource('/employee', App\http\Controllers\EmployeeController::class)->except('show');;
Route::resource('/company', App\http\Controllers\CompanyController::class)->except('show');;

// export pdf
Route::get('/exportpdf', [EmployeeController::class, 'exportpdf'])->name('exportpdf');

// export excel
Route::get('/exportExcel', [EmployeeController::class, 'exportExcel'])->name('exportExcel');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class company extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class employee extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

// use App\Models\employee;

use App\Models\company;
use Illuminate\Http\Request;
use PDF;

class CompanyController extends Controller
{
    public function index()
    {
        return view('company.index', [
            'data' => company::all()
        ]);
    }

    public function create()
    {
        return view('company.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'company' => 'required|string|max:255',
            'alamat' => 'required|string|max:255',
        ]);

        company::create($request->all());
        return redirect()->route('company.index')->with('success', 'Company has been added!');

        // dd($request->all());
    }
    public function edit(company $company)
    {
        return view('company.edit', compact('company'));
    }

    public function update(Request $request, company $company)
    {
        $request->validate([
            'company' => 'required|string|max:255',
            'alamat' => 'required|string|max:255',
        ]);

        $company->update($request->all());

        return redirect()->route('company.index')->with('success', 'Company telah berhasil diupdate');
    }

    public function destroy(company $company)
    {
        $company->delete();
        return redirect()->route('company.index')->with('success', 'data berhasil dihapus');
    }

    // public function exportpdf()
    // {
    //     $data = company::all();
    //     view()->share('data', $data);
    //     $pdf = PDF::loadview('dataPegawai-pdf');
    //     return $pdf->download('data.pdf');
    // }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Models\company;
use App\Models\employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Rap2hpoutre\FastExcel\FastExcel;
// use App\User;

class EmployeeController extends Controller
{
    public function index(Request $request)
    {
        $data = DB::table('employees')
        ->join('companies','companies.id','=','employees.company_id')
        ->select("employees.*","companies.company")
        ->paginate(9);

        return view('employee.index', compact('data'));
    }

    public function create()
    {
        return view('employee.create',[
            'companies' => company::all()
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string|max:255',
            'posisi' => 'required|string|max:255',
            'company_id' => 'required',
        ]);
        employee::create($request->all());
        return redirect()->route('employee.index')->with('success', 'data berhasil ditambahkan');

        // dd($request->all());
    }

    public function edit(employee $employee)
    {
        return view('employee.edit',[
            'employee' => $employee,
            'companies' => company::all(),
        ]);
    }

    public function update(Request $request, employee $employee)
    {
        $request->validate([
            'nama' => 'required|string|max:255',
            'posisi' => 'required|string|max:255',
            'company_id' => 'required',
        ]);
        $employee->update($request->all());
        return redirect()->route('employee.index')->with('success', 'data berhasil diupdate');
    }

    public function destroy(employee $employee)
    {
        $employee->delete();
        return redirect()->route('employee.index')->with('success', 'data berhasil dihapus');
    }

    public function exportpdf()
    {
        $data = DB::table('employees')
        ->join('companies','companies.id','=','employees.company_id')
        ->select("employees.*","companies.company")->get();

        view()->share('data', $data);
        $pdf = PDF::loadview('employee.export-pdf');
        return $pdf->download('Employee.pdf');
    }

    public function exportExcel()
    {
        // $data = employee::all();

        return (new FastExcel(
            DB::table('employees')
            ->join('companies','companies.id','=','employees.company_id')
            ->select("employees.*","companies.company")->get()
            ))->download('Employee.xlsx', function ($data) {
            return [
                'id' => $data->id,
                'nama' => $data->nama,
                'Posisi' => $data->posisi,
                'Perusahaan' => $data->company,

            ];
        });
    }
}

resources/views/company/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Company</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h2 class="text-center my-4">Tambah Data Company</h2>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <div class="card">
            <div class="card-body">
              <form action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Nama</label>
                  <input type="text" name="company" class="form-control" id="company" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                  <label for="exampleInputEmail1" class="form-label">Alamat</label>
                  <input type="text" name="alamat" class="form-control" id="alamat" aria-describedby="emailHelp">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/company/edit.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD LARAVEL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h2 class="text-center my-4">Edit Data Employee</h2>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <div class="card">
            <div class="card-body">
              <form action="{{ route('company.update', $company->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="mb-3">
                    <label for="company" class="form-label">Nama</label>
                    <input type="text" class="form-control" id="company"
                    name="company">
                </div>
                <div class="mb-3">
                    <label for="alamat" class="form-label">Nama</label>
                    <input type="text" class="form-control" id="alamat"
                    name="alamat">
                </div>
                <button type="submit" class="btn btn-primary">Update Company</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/company/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Struktur Organisasi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h2 class="text-center my-4">Data Company</h2>
    <div class="container">
        <div class="row g-3 align-items-center mt-2">
            <div class="col-auto">
                <a href="{{ route('company.create') }}" class="btn btn-success">Tambah +</a>
            </div>
            <div class="col-auto">
                <a href="/" class="btn btn-primary">Data Pegawai</a>
            </div>
          </div>
      <div class="row">
        <div class="my-2">
          @if ($message = Session::get('success'))
            <div class="alert alert-success" role="alert">
              {{ $message }}
            </div>
          @endif
        </div>
        <table class="table table-striped text-center">
          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">Nama</th>
              <th scope="col">Alamat</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($data as $row)
            <tr>
              <th scope="row">{{ $row->id }}</th>
              <td>{{ $row->company }}</td>
              <td>{{ $row->alamat }}</td>
              <td>
                <a href="{{ route('company.edit',$row->id) }}" class="btn btn-primary">Edit</a>
                <form action="{{ route('company.destroy',$row->id)}}" method="post" class="d-inline">
                    @method('delete')
                    @csrf
                    <button class="btn btn-danger" onclick="return confirm('Are you sure ?')">
                    Delete
                    </button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/employee/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD LARAVEL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h2 class="text-center my-4">Tambah Data Employee</h2>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <div class="card">
            <div class="card-body">
              <form action="{{ route('employee.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="mb-3">
                  <label for="nama" class="form-label">Nama</label>
                  <input type="text" name="nama" class="form-control" id="nama" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                  <label for="posisi" class="form-label">Posisi</label>
                  <input type="text" name="posisi" class="form-control" id="posisi" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="company_id" class="form-tabel">Perusahaan</label>
                    <select class="form-select" name="company_id">
                        @foreach($companies as $company)
                        @if(old('company_id') == $company->id)
                           <option value="{{ $company->id }}" selected>{{ $company->company }}</option>
                           @else
                           <option value="{{ $company->id }}">{{ $company->company }}</option>
                           @endif
                        @endforeach
                    </select>
                  </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/employee/edit.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRUD LARAVEL</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <h2 class="text-center my-4">Edit Data Employee</h2>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <div class="card">
            <div class="card-body">
              <form action="{{ route('employee.update', $employee->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="mb-3">
                    <label for="nama" class="form-label">Nama</label>
                    <input type="text" name="nama" class="form-control" id="nama" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-3">
                    <label for="posisi" class="form-label">Posisi</label>
                    <input type="text" name="posisi" class="form-control" id="posisi" aria-describedby="emailHelp">
                  </div>
                  <div class="mb-3">
                      <label for="company_id" class="form-tabel">Perusahaan</label>
                      <select class="form-select" name="company_id">
                          @foreach($companies as $company)
                          @if(old('company_id') == $company->id)
                             <option value="{{ $company->id }}" selected>{{ $company->company }}</option>
                             @else
                             <option value="{{ $company->id }}">{{ $company->company }}</option>
                             @endif
                          @endforeach
                      </select>
                    </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/employee/export-pdf.blade.php
<!DOCTYPE html>
<html>
<head>
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
</style>
</head>
<body>

<h1>Data Perusahaan</h1>

<table id="customers">
  <tr>
    <th>ID</th>
    <th>Nama</th>
    <th>Posisi</th>
    <th>Perusahaan</th>
  </tr>
  @foreach ($data as $row){
    <tr>
      <th scope="row">{{ $row->id }}</th>
      <td>{{ $row->nama }}</td>
      <td>{{ $row->posisi }}</td>
      <td>{{ $row->company }}</td>
    </tr>
  }
  @endforeach
</table>

</body>
</html>

resources/views/employee/index.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Struktur Organisasi</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <h2 class="text-center my-4">Data Employee</h2>
    <div class="container">
      <a href="{{ route('employee.create') }}" class="btn btn-success">Tambah +</a>

      <div class="row g-3 align-items-center mt-2">
        <div class="col-auto">
          <a href="/exportpdf" class="btn btn-info">Export PDF</a>
        </div>
        <div class="col-auto">
          <a href="/exportExcel" class="btn btn-success">Export Excel</a>
        </div>
        <div class="col-auto">
          <a href="/company" class="btn btn-primary">Data Perusahaan</a>
        </div>
      </div>


      <div class="row">
        <div class="my-2">
          @if ($message = Session::get('success'))
            <div class="alert alert-success" role="alert">
              {{ $message }}
            </div>
          @endif
        </div>
        <table class="table table-striped text-center">
          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">Nama</th>
              <th scope="col">Posisi</th>
              <th scope="col">Perusahaan</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($data as $row)
            <tr>
              <th scope="row">{{ $row->id }}</th>
              <td>{{ $row->nama }}</td>
              <td>{{ $row->posisi }}</td>
              <td>{{ $row->company }}</td>
              <td>
                <a href="{{ route('employee.edit',$row->id) }}" class="btn btn-primary">Edit</a>
                <form action="{{ route('employee.destroy',$row->id)}}" method="post" class="d-inline">
                    @method('delete')
                    @csrf
                    <button class="btn btn-danger" onclick="return confirm('Are you sure ?')">
                    Delete
                    </button>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
        {{ $data->links() }}
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <script
    src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
    integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
    crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  </body>
  <script>
    $('.delete').click(function(){
      var pegawaiid = $(this).attr('data-id');
      var nama = $(this).attr('data-nama');
        swal({
          title: "Yakin!!",
          text: "Apakah kamu yakin ingin menghapus data " +nama+ " ",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
        if (willDelete) {
          window.location = "/delete/{id}"+nama+ " "
          swal("Data berhasil dihapus", {
            icon: "success",
          });
        } else {
          swal("Data tidak jadi terhapus");
        }
      });
    });
  </script>

  <script>
    // toastr.success('Have fun storming the castle!', 'Miracle Max Says')
  </script>
</html>